name: Sync NELC Website

on:
  schedule:
    - cron: "*/6 * * * *"
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.PAT }}
          fetch-depth: 0

      - name: Sync Fork
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git remote add upstream https://github.com/NELC-Official/NELC-Official.github.io.git  
          git fetch upstream
          
          cp -r .github /tmp/github_backup
          
          git checkout main
          git reset --hard upstream/main
          
          rm -rf .github
          cp -r /tmp/github_backup .github
          
          git add .github
          git commit -m "The site has been synchronized"
          
          git push origin main --force
